name       : sysstat
version    : 12.2.2
release    : 15
source     :
    - https://github.com/sysstat/sysstat/archive/v12.2.2.tar.gz : 0d73d495eed18ab4bf77dbce6a2e94ce5276bd736906972c067b55882833e61a
license    : GPL-2.0-or-later
component  : system.utils
summary    : System performance tools for the Linux operating system
description: |
    The sysstat package contains the sar, sadf, mpstat, iostat, tapestat, pidstat, cifsiostat and sa tools for Linux.
    The sar command collects and reports system activity information.
    The information collected by sar can be saved in a file in a binary format for future inspection. The statistics reported by sar concern I/O transfer rates, paging activity, process-related activities, interrupts, network activity, memory and swap space utilization, CPU utilization, kernel activities and TTY statistics, among others. Both UP and SMP machines are fully supported.
    The sadf command may  be used to display data collected by sar in various formats (CSV, XML, etc.).
    The iostat command reports CPU utilization and I/O statistics for disks.
    The tapestat command reports statistics for tapes connected to the system.
    The mpstat command reports global and per-processor statistics.
    The pidstat command reports statistics for Linux tasks (processes).
    The cifsiostat command reports I/O statistics for CIFS file systems.
builddeps  :
    - lm_sensors-devel
setup      : |
    %configure --sysconfdir=/etc/sysstat \
               --enable-copy-only \
               --enable-install-cron \
               --with-systemdsystemunitdir=%libdir%/systemd/system
build      : |
    %make
install    : |
    %make_install

    mkdir -p $installdir/usr/share/defaults/etc/profile.d
    install -m 00644 $pkgfiles/60-colorsysstat.sh $installdir/usr/share/defaults/etc/profile.d

    # Do not ship /var/log in package
    rm -rfv $installdir/var
    install -D -m 00644 $pkgfiles/sysstat.tmpfiles $installdir/%libdir%/tmpfiles.d/sysstat.conf
